#!/usr/bin/env bash
set -e

if [ ! -z "$(which snap)" ]; then
    sudo apt install snapd
fi

echo "Installing: keepassxc"
sudo snap install keepassxc
sudo snap connect keepassxc:password-manager-service
sudo snap connect keepassxc:raw-usb
sudo snap connect keepassxc:removable-media

sudo apt install -y \
    nextcloud-desktop \
    yubioath-desktop \
    yubikey-manager-qt \
    yubikey-personalization \
    alacritty

nvim_path="$(which nvim)"
if [ ! -z "$nvim_path" ]; then
    sudo update-alternatives --install /usr/bin/editor editor "$nvim_path" 100
fi

alacritty_path="$(which alacritty)"
if [ ! -z "$alacritty_path" ]; then
    sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator "$alacritty_path" 100
fi

echo "Done. Installed snaps and configured KeePassXC interfaces."
