filetype plugin on
filetype indent on
syntax on
set hlsearch
set rnu

" the following line is needed to load python3 and not python2
" py3 import sys
if has('gui_running')
  set guifont=Ubuntu\ Mono\ 12
  set grepprg=grep\ -nH\ $*
  filetype indent on
endif

set guioptions-=T
set guioptions-=r

" Store swp/backup file in one place
if !isdirectory($HOME."/.vim/backup")
    call mkdir($HOME."/.vim/backup", "", 0770)
endif
set backupdir=$HOME/.vim/backup//
if !isdirectory($HOME."/.vim/undodir")
    call mkdir($HOME."/.vim/undodir", "", 0770)
endif
set undofile
set undodir=~/.vim/undodir
if !isdirectory($HOME."/.vim/swap")
    call mkdir($HOME."/.vim/swap", "", 0700)
endif
set directory=$HOME/.vim/swap//


fun! ToggleUmlauts()
  if !exists("g:toggleUmlauts_isEnabled")
    let g:toggleUmlauts_isEnabled=0
  endif

  if !g:toggleUmlauts_isEnabled
    let g:toggleUmlauts_isEnabled=1
    imap <buffer> "a ä
    imap <buffer> "A Ä
    imap <buffer> "u ü
    imap <buffer> "U Ü
    imap <buffer> "o ö
    imap <buffer> "O Ö
    imap <buffer> "s ß
  else
    let g:toggleUmlauts_isEnabled=0
    iunmap <buffer> "a
    iunmap <buffer> "A
    iunmap <buffer> "u
    iunmap <buffer> "U
    iunmap <buffer> "o
    iunmap <buffer> "O
    iunmap <buffer> "s
  endif
endfun


autocmd FileType vue syntax sync fromstart
" let g:vue_disable_pre_processors=1

inoremap <F2> <esc>:call ToggleUmlauts()<cr>a
let g:syntastic_cpp_compiler_options = ' -std=c++17'

set list lcs=trail:·,tab:»·
set modeline

" Enable completion where available.
" This setting must be set before ALE is loaded.
"
" You should not turn this setting on if you wish to use ALE as a completion
" source for other completion plugins, like Deoplete.
let g:ale_completion_enabled = 0
set omnifunc=ale#completion#OmniFunc
let g:ale_completion_tsserver_autoimport = 1

let g:ale_linters = {
  \ 'javascript': ['eslint', 'tsserver'],
  \ 'vue': ['eslint', 'vls'],
  \ 'typescript': ['eslint', 'tsserver'],
  \ 'perl': ['perlcritic'],
  \ }
let g:ale_fixers = {'javascript': ['eslint'], 'vue': ['eslint'], 'typescript': ['eslint']}
let g:ale_fix_on_save = 1
let g:ale_java_javac_classpath="/usr/share/java/*:."

" let g:ale_perl_perl_options = '-c -Mwarnings -Ilib -It/lib'
let g:ale_perl_perlcritic_showrules = 1

if filereadable("/usr/share/doc/fzf/examples/fzf.vim")
  source /usr/share/doc/fzf/examples/fzf.vim
else
  set rtp+=~/.fzf
endif

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

nmap <C-p> :Files<CR>
nnoremap <leader>b :Buffers<CR>

highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1

" for node.js fs.watch
set backupcopy=yes

" configure spell
" highlight clear SpellBad
" highlight SpellBad cterm=underline ctermfg=Red
" highlight SpellBad gui=undercurl guifg=Red

autocmd BufNewFile,BufRead *.txt   set filetype=wiki
autocmd BufNewFile,BufRead *.md   set filetype=markdown

nmap <leader>a :Ack! "\b<cword>\b" <CR>

" Put these lines at the very end of your vimrc file.

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
