# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias lgrep='grep -Ri --exclude-dir={node_modules,pub}'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias vpn='sudo openvpn *.ovpn'
alias gpg=gpg2

# some aliases for git
alias gitc='git commit -p'
alias gitp='git push'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias wifialive='arping -I wlp4s0 10.10.10.1'
alias createpr='gh pr create; gh pr merge --squash --auto'
alias k='kubectl'
complete -o default -F __start_kubectl k
