# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias lgrep='grep -Ri --exclude-dir={node_modules,pub}'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias vpn='sudo openvpn *.ovpn'
alias gpg=gpg2

# some aliases for git
alias gitc='git commit -p'
alias gitp='git push'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias wifialive='arping -I wlp4s0 10.10.10.1'
alias createpr='gh pr create; gh pr merge --squash --auto'
alias k='kubectl'
complete -o default -F __start_kubectl k

alias qrestic-init="restic -r rclone:onedrive:backup init"
alias qrestic-backup="restic -r rclone:onedrive:backup backup $HOME/Documents/ $HOME/Music/ $HOME/Pictures/"
alias qeditor-set="sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60"
alias firefox-backup="tar -C $HOME -jcvf $HOME/Documents/firefox-browser-profile.tar.bz2 $HOME/snap/firefox"
alias firefox-restore="tar -xvf $HOME/Documents/firefox-browser-profile.tar.bz2 -C $HOME"
alias chrome-enable-schreenshare="echo 'chrome://flags/#enable-webrtc-pipewire-capturer'"
alias ovpn-import-qwiki-config="nmcli connection import type openvpn file $HOME/Documents/vpn.modac.eu.ovpn"
alias install-asdf="git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.0"
